config/routes.rb
Rails.application.routes.draw do
  root 'guest_pages#home'
  get '/admin', to: 'admin_pages#home'
  get '/income', to: 'admin_pages#income'
  get '/settings', to: 'admin_pages#settings'
  get '/guest', to: 'sessions_for_guests#create', as: 'new_guest'
  get '/guest_orders', to: 'orders#guest_orders', as: 'guest_orders'
  get '/see_order', to: 'orders#see_order', as: 'see_order'
  get '/cart', to: 'orders#cart', as: 'cart'
  get '/see_order_admin', to: 'orders#see_order_admin', as: 'see_order_admin'
  get '/login', to: 'session_for_admin#new', as: 'login'
  post '/login', to: 'session_for_admin#create'
  resources :items
  resources :orders
  resources :ordered_items
end

app/views/shared/_footer_admin.html.haml
%footer.footer-admin
  .footer-logo
    = link_to "LOGO", admin_path
  .footer-info
    info

app/views/shared/_footer_guest.html.haml
%footer.footer
  .footer-logo 
    = link_to "LOGO", root_path
  .footer-info
    info

app/views/shared/_header_admin.html.haml
%header.header-admin
  .header-logo.header-item
    = link_to "LOGO", admin_path
  .dropdown-nav.header-item
    %span.menu MENU
    %ul.header-nav
      %li= link_to "Home", admin_path
      %li= link_to "Flowers", items_path
      %li= link_to "Orders", orders_path

app/views/shared/_header_guest.html.haml
%header.header
  .header-logo.header-item
    = link_to "LOGO", root_path
  .dropdown-nav.header-item
    MENU
    %ul.header-nav
      %li= link_to "Flori", root_path
      %li= link_to "Orders", guest_orders_path 
  .cart-wrapper.header-item
    = link_to "Cart", cart_path