config/routes.rb
Rails.application.routes.draw do
  root 'guest_pages#home'
  get '/admin', to: 'admin_pages#home'
  get '/income', to: 'admin_pages#income'
  get '/settings', to: 'admin_pages#settings'
  get '/guest', to: 'sessions_for_guests#create', as: 'new_guest'
  get '/guest_orders', to: 'orders#guest_orders', as: 'guest_orders'
  get '/see_order', to: 'orders#see_order', as: 'see_order'
  get '/cart', to: 'orders#cart', as: 'cart'
  get '/see_order_admin', to: 'orders#see_order_admin', as: 'see_order_admin'
  get '/login', to: 'session_for_admin#new', as: 'login'
  post '/login', to: 'session_for_admin#create'
  resources :items
  resources :orders
  resources :ordered_items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :guest
  has_many :ordered_items
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :admin, only: [:index, :see_order_admin, :edit]

  def index
    if (filter = params[:filter])
      @orders = Order.where("#{filter}" => true).paginate(page: params[:page], per_page: 7)
    else
      @orders = Order.all.paginate(page: params[:page], per_page: 7)
    end
  end

  def guest_orders
    if (filter = params[:filter])
      @orders = current_guest.orders.where("#{filter}" => true).paginate(page: params[:page], per_page: 7)
    else
      @orders = current_guest.orders.paginate(page: params[:page], per_page: 7)
    end
  end

  def see_order
    @order = current_guest.orders.where(id: params[:id])
    if !@order[0].nil?
      @ordered_items = @order[0].ordered_items
    end
    if !@ordered_items.nil?
      @items = @ordered_items.map { |n| n.item.name }
    end
  end

  def see_order_admin
    @order = Order.find(params[:id])
    @ordered_items = @order.ordered_items
    if !@ordered_items.nil?
      @items = @ordered_items.map { |n| n.item.name }
    end
  end

  def cart
    @cart_order = current_guest.orders.where(cart: true)
    if !@cart_order[0].nil?
      @ordered_items = @cart_order[0].ordered_items
    end
    if !@ordered_items.nil?
      @items = @ordered_items.map { |n| n.item.name }
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if params[:order1][:state] == "canceled"
      @order.canceled = true
      @order.description = "canceled"
    else
      @order.canceled = false
    end

    if params[:order1][:state] == "pending"
      @order.pending = true
      @order.description = "pending"
    else
      @order.pending = false
    end
    
    if params[:order1][:state] == "cart"
      @order.cart = true
      @order.description = "cart"
    else
      @order.cart = false
    end

    if params[:order1][:state] == "checkout"
      @order.checkout = true
      @order.description = "checkout"
    else
      @order.checkout = false
    end

    if params[:order1][:state] == "delivered"
      @order.delivered = true
      @order.description = "delivered"
    else
      @order.delivered = false
    end
    
    @order.save
    if !current_admin.nil?
      redirect_to orders_path
    elsif !current_guest.nil?
      redirect_to guest_orders_path
    else
      redirect_to root_path
    end
  end

  private

    def admin
      redirect_to root_path unless is_admin?
    end 

    def order_params
      params.require(:order1).permit(:cart, :checkout, :pending, :canceled, :delivered)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_orders.html.haml
%table
  %tr
    %th ID
    %th Description
    %th Cart
    %th Checkout
    %th Pending
    %th Canceled
    %th Delivered
    %th Created_at
    %th Updated_at
    %th Details
    %th Edit
  - @orders.each do |n|
    %tr
      %td= n.id
      %td= n.description
      %td= n.cart
      %td= n.checkout
      %td= n.pending
      %td= n.canceled
      %td= n.delivered
      %td= n.created_at
      %td= n.updated_at
      - if !n.cart
        - if is_admin?
          %td= link_to "open", see_order_admin_path(id: n.id)
        - else
          %td= link_to "open", see_order_path(id: n.id)
      - else
        %td= link_to "open", cart_path
      %td= link_to "edit", edit_order_path(id: n.id)

app/views/orders/cart.html.haml
%h1
  Cart
- if !@ordered_items.nil?
  %table
    %tr
      %th Item
      %th Quantity 
      %th Amount of money
      %th Update
      %th Delete
    - count = 0
    - @ordered_items.each do |n|
      %tr
        %td= @items[count]
        %td= n.quantity
        %td= n.amount_of_money
        %td= link_to "Update", edit_ordered_item_path(n.id) 
        %td= link_to "Delete", n, method: :delete, data: {confirm: "Are you sure"}
      - count = count + 1
  .checkout-btn-wrapper
    = form_for :order1, url: order_path(@cart_order[0].id), method: :patch do |f|
      = f.hidden_field :state, value: "pending"
      = f.submit "Checkout", class: "button" 
- else
  .empty
    Your cart is empty

app/views/orders/edit.html.haml
= form_for :order1, url: order_path(@order.id), method: :patch do |f|

  = f.radio_button :state, "canceled", checked: true
  = label :state_cancel, "Cancel"

  = f.radio_button :state, "pending"
  = label :state_pending, "Pending"

  = f.radio_button :state, "cart"
  = label :state_cart, "Cart"

  = f.radio_button :state, "checkout"
  = label :state_checkout, "Checkout"

  = f.radio_button :state, "delivered"
  = label :state_completed, "Delivered"

  = f.submit "Change" 

app/views/orders/guest_orders.html.haml
%h1 Orders
.orders-wrapper
  .orders-filter-wrapper
    .orders-filter
      Filter by:<br>
      %ul
        %li= link_to "Pending", guest_orders_path(filter: "pending") 
        %li= link_to "Delivered", guest_orders_path(filter: "delivered")
        %li= link_to "All", guest_orders_path
  .orders-result-wrapper
    - if @orders.count > 0
      .orders-result
        = render "orders"
      .page-form
        = will_paginate @orders
    - else
      No orders...

app/views/orders/index.html.haml
%h1 Orders
.orders-wrapper
  .orders-filter-wrapper
    .orders-filter
      Filter by:<br>
      %ul
        %li= link_to "Pending", orders_path(filter: "pending") 
        %li= link_to "Delivered", orders_path(filter: "delivered")
        %li= link_to "All", orders_path
  .orders-result-wrapper
    .orders-result
      = render "orders"
    .page-form
      = will_paginate @orders

app/views/orders/see_order.html.haml
- if !@ordered_items[0].nil?
  - if @ordered_items[0].order.cart?
    %p Cart
  - else
    %p Pending
  %table
    %tr
      %th Item
      %th Quantity 
      %th Amount of money
      %th Update
      %th Delete
    - count = 0
    - @ordered_items.each do |n|
      %tr
        %td= @items[count]
        %td= n.quantity
        %td= n.amount_of_money
        %td= link_to "Update", edit_ordered_item_path(n.id) 
        %td= link_to "Delete", n, method: :delete, data: {confirm: "Are you sure"}
      - count = count + 1
  - if @order[0].pending
    .checkout-btn-wrapper
      = form_for :order1, url: order_path(@order[0].id), method: :patch do |f|
        = f.hidden_field :state, value: "delivered"
        = f.submit "Complete", class: "button" 
- else
  .empty
    Your order is empty

app/views/orders/see_order_admin.html.haml
- if !@ordered_items[0].nil?
  - if @ordered_items[0].order.cart?
    %p Cart
  - else
    %p Pending
  %table
    %tr
      %th Item
      %th Quantity 
      %th Amount of money
      %th Update
      %th Delete
    - count = 0
    - @ordered_items.each do |n|
      %tr
        %td= @items[count]
        %td= n.quantity
        %td= n.amount_of_money
        %td= link_to "Update", edit_ordered_item_path(n.id) 
        %td= link_to "Delete", n, method: :delete, data: {confirm: "Are you sure"}
      - count = count + 1
  - if @order.pending
    .checkout-btn-wrapper
      = form_for :order1, url: order_path(@order.id), method: :patch do |f|
        = f.hidden_field :state, value: "delivered"
        = f.submit "Complete", class: "button" 
- else
  .empty
    Your order is empty