config/routes.rb
Rails.application.routes.draw do
  root 'guest_pages#home'
  get '/admin', to: 'admin_pages#home'
  get '/income', to: 'admin_pages#income'
  get '/settings', to: 'admin_pages#settings'
  get '/guest', to: 'sessions_for_guests#create', as: 'new_guest'
  get '/guest_orders', to: 'orders#guest_orders', as: 'guest_orders'
  get '/see_order', to: 'orders#see_order', as: 'see_order'
  get '/cart', to: 'orders#cart', as: 'cart'
  get '/see_order_admin', to: 'orders#see_order_admin', as: 'see_order_admin'
  get '/login', to: 'session_for_admin#new', as: 'login'
  post '/login', to: 'session_for_admin#create'
  resources :items
  resources :orders
  resources :ordered_items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :ordered_items
  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
  validates :description, presence: true, length: { maximum: 50 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :admin

  def index
    @items = Item.all.paginate(page: params[:page], per_page: 7)
  end
 
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      redirect_to items_path
    else
      render 'edit'
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to items_path
  end

  private
    def admin
      redirect_to root_path unless is_admin?
    end

    def item_params
      params.require(:item).permit(:name, :description, :price)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error_messages.html.haml
%ul
  = @item.errors.full_messages.each do |msg|
    %li= msg

app/views/items/_item.html.haml
.result-info
  %ul
    %li= item.name
    %li= "Price: #{item.price}"
    - if item.available?
      %li Available: Yes
    - else
      %li Available: No
    %li= "Sold: #{item.sold}"
  .btn
    = link_to "BUY", new_ordered_item_path(item_id: item.id)

app/views/items/_items.html.haml
%table
  %tr
    %th ID
    %th Name
    %th Description
    %th Price 
    %th Sold
    %th Available
    %th Created_at
    %th Updated_at
    %th Edit
    %th Destroy
  - @items.each do |n|
    %tr
      %td= n.id
      %td= n.name
      %td= n.description
      %td= n.price
      %td= n.sold
      %td= n.available
      %td= n.created_at
      %td= n.updated_at
      %td= link_to "Edit", edit_item_path(n.id)
      %td= link_to "Destroy", n, method: :delete, data: { confirm: "Are you sure?" }

app/views/items/edit.html.haml
= form_for @item do |f|
  = render 'error_messages'
  
  = f.label :name
  = f.text_field :name

  = f.label :description
  = f.text_area :description
 
  = f.label :price
  = f.text_field :price

  = f.submit "Add"

app/views/items/index.html.haml
%h1 Flowers
.flowers-wrapper
  .flowers-result-wrapper
    .flowers-add
      = link_to "Add", new_item_path 
    .flowers-result
      = render "items"
    .page-form
      = will_paginate @items

app/views/items/new.html.haml
= form_for @item do |f|
  = render 'error_messages'
  
  = f.label :name
  = f.text_field :name

  = f.label :description
  = f.text_area :description
 
  = f.label :price
  = f.text_field :price

  = f.submit "Add"